security:
    password_hashers:
        App\Entity\AdminUser:
            algorithm: auto

    providers:
        admin_user_provider:
            entity:
                class: App\Entity\AdminUser
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: admin_user_provider

        api:
            pattern: ^/api
            stateless: true
            provider: admin_user_provider
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password

    access_control:
        - { path: ^/api, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            App\Entity\AdminUser:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
